### ISSUE TITLE
removeTag not Working

### ISSUE THREAD

**Issue by anjusr** [pulimento/TagListView-ObjC#4]
i couldn't remove the tag from tagListView by using this line [tagListView removeTag:@"meow"];

**Comment by anjusr** [comment]
Ok, Got it.. it should be index >= 0 in for-loop condition inside removeTag method.

**Comment by pulimento** [comment]
If you are so kind, please made me a pull request and I accept it. Thanks
in advance

2016-11-09 10:03 GMT+01:00 anjusr notifications@github.com:

> Ok, Got it.. it should be index >= 0 in for-loop condition inside
> removeTag method.

**Comment by pulimento** [comment]
Seems that you are OK now, I'm closing this issue. Please let me know if the issue is not solved
